version: "3.8"
services:
  server:
    build: ./server
    container_name: shay_server
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Provide your MongoDB connection string below or via .env
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5000:5000"
    volumes:
      # Persist generated invoices and logs if needed
      - ./server/invoices:/app/invoices
      - ./server/log.txt:/app/log.txt
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: shay_client
    ports:
      - "3000:80"
    depends_on:
      - server

  mongo:
    image: mongo:6
    container_name: shay_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: